### ISSUE TITLE
可以出个移动端设备使用这个的教程吗？

### ISSUE THREAD

**Issue by zippozeng** [ossrs/tc-ui#1]
是在linux服务器运行这个之后，然后在linux服务器开个热点？在移动端连上这个热点进行测试吗？

**Comment by winlinvip** [comment]
移动端是有一些app的，你可以网上找找。

如果不方便在移动端直接设置，可以反向在服务器设置。比如如果你要用移动端推流到SRS，可以在SRS所在的linux服务器上设置弱网，效果一样的。
